---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: collectd
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::server_graphite]
    - recipe[ktc-monitor::server_collectd]
    - recipe[ktc-collectd::client_collectd]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
