---
driver_plugin: vagrant
# if you want to use chef-zero instead of solo-search
# uncomment this
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ubuntu]
    - recipe[ktc-monitor::server_collectd]
  attributes:
    monitor:
      recipes_server_collectd:
        - graphite
        - collectd::server
        - ktc-collectd::client_graphite

clusters:
  default:
    - default
