---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[ktc-monitor::server_graphite]
    - recipe[ktc-monitor::server_collectd]

clusters:
  default:
    - default
